#
## Developer Dependencies and Requirements
#

[project.optional-dependencies]
dev = [  # development dependencies, pip install with: pip install mano[dev]
    "build",
    "lxml-stubs",
    "mypy",
    "pytest==8.4.0",
    "responses",
    "ruff",
    "twine",
    "types-python-dateutil",
    "types-requests",
]


#
## Pytest configuration
#


[tool.pytest.ini_options]
addopts = "-ra"
# minversion = "9.0.0"
testpaths = [
    "tests",
]


#
## Linters Etc.
#


#
# Ruff - general purpose python linter++
#
[tool.ruff]
line-length = 105
indent-width = 4

[tool.ruff.format]
indent-style = "space"  # use spaces for indentation
line-ending = "lf"  # use \n for line endings

[tool.ruff.lint.pycodestyle]
max-line-length = 120  # maximum line length

[tool.ruff.lint]
future-annotations = true

select = [  # (linting directives to enable)
    "E",       # pycodestyle errors
    "W",       # pycodestyle warnings
    "F",       # pyflakes codes
    "UP",      # pyupgrade codes
    "COM818",  # trailing-comma-on-bare-tuple
    "A",       # flake8-annotations codes
]

ignore = [  # (linting directives to ignore)
    "E701",  # multiple statements on one line - one line Exception subclasses are great.
    "W293",  # blank line contains whitespace
]

#
# isort - import sorting
#
[tool.isort]
line_length = 100
use_parentheses = true
remove_redundant_aliases = true
star_first = true
multi_line_output = 10  # aka HANGING_INDENT_WITH_PARENTHESES
combine_as_imports = true
lines_after_imports = 2
lines_between_types = 0
# dont_order_by_type = true  # not supported in config file???

known_third_party = [  # Force these libraries to a special spot in import order (second to bottom)
    "forest",
    "requests",
]

known_first_party = [  # Force these libraries to a special spot in import order (bottom)
    "mano",
]


#
# MyPy - Type checking
#
[tool.mypy]
packages = "mano"

[[tool.mypy.overrides]]        # trying to replicate this from the mypy.ini
module = ["cryptease"]         #   [mypy-cryptease]
ignore_missing_imports = true  #   ignore_missing_imports = true


#
## Mano Project Information
#


[project.urls]
Homepage = "https://github.com/onnela-lab/mano#Mano"
Issues = "https://github.com/onnela-lab/mano/issues/39"
Source = "https://github.com/onnela-lab/mano"


# Structural Information
[project]
readme = "README.md"
license = {file = "LICENSE"}

# Version
version = "0.7.0-dev"

# Python Version Requirement
requires-python = ">=3.10"

# Authorship
name = "mano"
description = "Python API for the Beiwe Research Platform"
authors = [
    {name = "Onnela Lab", email = "onnela.lab@gmail.com"}
]
maintainers = [
    {name = "Onnela Lab", email = "onnela.lab@gmail.com"}
]

# PyPi Information
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]


#
## Core Dependencies and Build System Configuration
#


dependencies = [  # this is underneath [project] but is about the build / dependencies systems
    "cryptease",
    "lxml",
    "python-dateutil",
    "pyzstd",
    "requests",
]

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["mano*"]

[tool.setuptools.package-data]
"mano" = ["config.json"]
