title: Mano

repository: onnela-lab/mano


# theme: midnight

remote_theme: pages-themes/midnight@v0.2.0

markdown: GFM 
plugins:
- jekyll-gfm-admonitions
- jekyll-optional-front-matter
- jekyll-remote-theme

exclude: 
  - "**/*.ts" # Exclude source code files!
  - "**/*.js"
  - "*.ts" # Also those in the root directory!
  - "*.js"
  - "*.json" # Don't forget about assets!
  - node_modules/ # And large vendored directories
  # And these ignore all the artifacts the build produces:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
